{
  "count": 39,
  "results": [{
    "listing_id": 152178330,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Pearls and leather earings, Australian golden pearls, beach jewelry, leather jewelry, boho jewelry, cultured pearls, silver hooks",
    "description": "Simple earings composed with two Australian golden cultured pearls, 2 silver hooks and my precious hand rolled leather with traditional sailor knots.\r\n\r\nChic and organic.\r\n\r\nThe earings you will buy will be slightly different from the pictures (totally organique materials), i garantee that the pearls will be same quality and size as well as the silver hooks.\r\n\r\nThis earings is available is Black Tahitian pearl AND White Australian pearl too, please inquire.\r\n\r\nStyle earings \r\nPearl size  10.5 mm \r\nPearl quantity 2 \r\nLength 3 cm \r\nMaterial Australian pearls \/ silver \/ leather \r\nPearl shape circled \r\nPearl grade C\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403161087,
    "ending_tsz": 1413701887,
    "original_creation_tsz": 1369501287,
    "last_modified_tsz": 1403161087,
    "price": "160.00",
    "currency_code": "USD",
    "quantity": 4,
    "tags": ["Tahitian pearl", "australian pearl", "cultured pearls", "black pearl", "leather jewelry", "st barts", "white pearl", "golden pearls", "treasures", "caribbean treasures", "pearls earings", "beach jewelry", "pearls jewelry"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "australian pearl", "cultured pearls", "black pearl", "leather jewelry", "leather necklace", "st barts", "white pearl", "golden pearls", "treasures", "caribbean treasures", "leather earings", "pearls earings"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1393690258,
    "url": "https:\/\/www.etsy.com\/listing\/152178330\/pearls-and-leather-earings-australian?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 432,
    "num_favorers": 35,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 159341004,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151567,
    "title": "Tumbled ancient sea glass grape necklace, genuine ancient sea glass, beach jewelry, bubble sea glass, sea glass and leather, boho jewelry.",
    "description": "Unique and very natural design for this wonderful on request design. Grape of 10 superb genuine ancient bubble sea glass from northern England dates which have been rolled by the sea from at least 90 to 160 years.\r\n\r\nI carefully drilled and mounted them with my precious hand rolled leather and traditional sailors knots.\r\n\r\nTotally organic, easy, chic and noisy, rough treasures but knotted in a sophisticated way\u2026a must. \r\n\r\nMADE TO ORDER !!! The necklace you will received will be always slightly different than this one : all my materials are unique !\r\n\r\nThe necklace is using an 11th bubble sea glass as clasp which make the composition adaptable from a long sautoir to a crew neck with a falling pearls on the side of the bubbles, just slide all the pearls and adapt the lenght to the mood of the day.\r\n\r\nSea glass of this quality can be found in only one beach in the entire world. imagine yourself carrying with you a piece of 150 years old testimony of the finest samples of Victorian and Edwardian coloured glass, shaped by nature, rolled by more than a century of waves to create a beautiful one of a kind piece of eco-friendly, recycled jewellery. \r\n\r\nPlease see below for full explanation :\r\n\r\n&quot;Candlish Bottleworks and glass foundry&quot; was built on the cliffs at Seaham, County Durham, and began producing glass in 1853. It made almost every colour imaginable for medicine and poison bottles, vases and homewares and everyday drinks bottles. Reds, blues, yellows and even opaque glass were made in its furnaces, using materials as Selenium, Arsenic, Gold and even Uranium, to be mixed into the glass to try and achieve perfection, whether it be of a specific colour or a clarity of glass.\r\n\r\nA lot of the glass remnants were tossed over the cliffs into the cliff beds, some say to reinforce the eroding cliffs or to dump unwanted glass (melted together into &quot;gobs&quot; and hurled into the sea). Either way the result, after more than a century, is an magical resource of perfect, polished pieces of unique glass. The Victorian glass factory closed sometime in the early 1920s leaving the waves of times doing their jobs\u2026for our pleasure. \r\n\r\nPearl quantity\t11\r\nMaterial\tBubble sea glass \/ leather\r\nLength\tAdaptable\r\nStyle\tNecklace\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403095668,
    "ending_tsz": 1413636468,
    "original_creation_tsz": 1376252595,
    "last_modified_tsz": 1403096202,
    "price": "400.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "cultured pearls", "black pearl", "leather jewelry", "leather necklace", "st barts", "treasures", "caribbean treasures", "bubble sea glass", "seaham sea glass", "treasure necklace", "sea glass necklace", "treasure"],
    "category_path": ["Jewelry", "Necklace"],
    "category_path_ids": [68887482, 69151567],
    "materials": ["Tahitian pearl", "australian pearl", "cultured pearls", "leather jewelry", "leather necklace", "st barts", "treasures", "caribbean treasures", "sea glass", "seaham bubble glass", "sea glass and leather", "beach jewelry", "bubble sea glass"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1393526559,
    "url": "https:\/\/www.etsy.com\/listing\/159341004\/tumbled-ancient-sea-glass-grape-necklace?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 1473,
    "num_favorers": 123,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 152176816,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Pearl and leather bracelet, seaglass bubble, tahitian pearl on leather,boho jewelry, beach jewelry, leather jewelry, antique seaglass.",
    "description": "Unique and precious bracelet made to order, with a genuine ancient bubble seaglass from Nothern England. This seaglass bubble is between minimum 90 to 160 years old and is mounted with my precious hand rolled leather and traditioanl sailor knots. This bracelet is using a Round Tahitian grey pearl as clasp.\r\n\r\nSea glass of this quality can be found in only one beach in the entire world. imagine yourself carrying with you a piece of 150 years old testimony of the finest samples of Victorian and Edwardian coloured glass, shaped by nature, rolled by more than a century of waves to create a beautiful one of a kind piece of eco-friendly, recycled jewellery. \r\n\r\nATTENTION !! Made to order !!! The bracelet you will received will look the same but will be slightly different ! All my materials are unique : Tahitian pearl, handmade leather, bubble seaglass...\r\n\r\n Please see below for full explanation.\r\n\r\nCandlish Bottleworks and glass foundry was built on the cliffs at Seaham, County Durham, and began producing glass in 1853.  It made almost every colour imaginable for medicine and poison bottles, vases and homewares and everyday drinks bottles. Reds, blues, yellows and even opaque glass were made in its furnaces, using materials as Selenium, Arsenic, Gold and even Uranium, to be mixed into the glass to try and achieve perfection, whether it be of a specific colour or a clarity of glass.\r\n\r\nA lot of the glass remnants were tossed over the cliffs into the cliff beds, some say to reinforce the eroding cliffs or to dump unwanted glass (melted together into &quot;gobs&quot; and hurled into the sea). Either way the result, after more than a century, is an magical resource of perfect, polished pieces of unique glass. The Victorian glass factory closed sometime in the early 1920s leaving the waves of times doing their jobs\u2026for our pleasure.\r\n\r\nLength 19 cm \r\nPearl size  9.5 mm \r\nMaterial Tahitian pearl \/ seaglass \/ leather \r\nStyle Bracelet \r\nPearl grade C+ \r\nPearl shape Round \r\nPearl quantity 1\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403095668,
    "ending_tsz": 1413636468,
    "original_creation_tsz": 1369500049,
    "last_modified_tsz": 1403096634,
    "price": "205.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "cultured pearls", "black pearl", "leather jewelry", "st barts", "white pearl", "treasures", "caribbean treasures", "leather bracelet", "seaglass", "beach jewelry", "seaglass bubble", "pearl bracelet"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "australian pearl", "cultured pearls", "black pearl", "leather jewelry", "leather necklace", "st barts", "white pearl", "golden pearls", "treasures", "caribbean treasures", "seaglass", "beach jewelry"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1393526588,
    "url": "https:\/\/www.etsy.com\/listing\/152176816\/pearl-and-leather-bracelet-seaglass?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 452,
    "num_favorers": 34,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 177760780,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Black tahitian pearls earings on leather beach jewelery boho leather design endless summer st barts, cultured black pearls, bohemian.",
    "description": "Bright, chic and huge Tahitian black pearls of 11.5 mm semi-baroque shiny drops, drilled and mounted on my handmade precious leather here in St Barts.\r\n\r\nEaring wires are made of sterling sliver and have been oxidized.\r\n\r\nPearl size  11.5 mm \r\nPearl shape half baroque \r\nMaterial Tahitian pearls \/ oxidized silver \/ leather \r\nPearl quantity 2 \r\nStyle earrings \r\nLength 4.5 cm \r\nPearl grade C \r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403095540,
    "ending_tsz": 1413636340,
    "original_creation_tsz": 1391177757,
    "last_modified_tsz": 1403095540,
    "price": "390.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "pearls earrings", "pearls and leather", "earring and leather"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "silver and leather", "pearls and leather", "leather and silver"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1401628823,
    "url": "https:\/\/www.etsy.com\/listing\/177760780\/black-tahitian-pearls-earings-on-leather?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 165,
    "num_favorers": 7,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 177533599,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Shooting stars earrings : Meteorites and vermeil genuine meteorites, leather gold and silver, beach jewelery, earring from out of space ; )",
    "description": "Warning !!! Earrings from out of space !\r\n\r\nUnique pair of earrings made with genuine shooting stars .Is it composed of two genuine m\u00e9t\u00e9orites also called &quot;chondrites&quot;, older than the creation of the surface of earth and some tiny, reeeally tiny faceted vermeil beads carefuly knotted of my leather on two oxidized silver hooks.\r\n\r\nYou know, the moment a shooting stars entering the atmosph\u00e8re ? this moment you open your eyes widely and make a wish ? You can cherish that moment ever and preciously carying it with you, all the time.\r\n\r\nGold vermeil, is sterling silver plated with gold. Gold vermeil is comparable to pure gold in appearance and artisanship but much more affordable.\r\n\r\nStyle necklace \r\nLength 4 cm \r\nMaterial meteorites \/ vermeil beads \r\n\r\nPlease see below for full explanation :\r\n\r\nChondrites come from parent bodies circulating between Mars and Jupiter and, as a result of violent collisions with asteroids, various fragments were sent to Sun. Some of these fragments crossed the orbit of the Earth and become meteorites. Treat them with respect, they are the oldest objects that you can touch on Earth. Chondrites are stony (non-metallic) meteoritesthat have not been modified due to melting or differentiation, of the parent body.\r\n\r\nThey are formed when various types of dust and small grains that were present in the early solar system accreted to form primitive asteroids (over 4,550 million years ago) .Their study provides important clues for understanding the origin and age of the Solar System, the synthesis of organic compounds, the origin of life or the presence of water on Earth. \r\n\r\nOne of their characteristics is the presence of chondrules, which are round grains formed by distinct minerals, that normally constitute between 20% and 80% of a chondrite by volume.Weapons and tools dated 3000BC analysis Revealed after a very particular composition, an alloy of iron and nickel &quot;iron meteorite.&quot; \r\n\r\nNecklace of beads and the first Egyptian dynasty back to 3200 BC found in Giza in 1911 were also made \u200b\u200ba &quot;meteoric iron&quot;.\r\n\r\nMany falling meteorites were recorded by Greek authors such as Diogenes of Apollonia, Pliny or Plutarch\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403095540,
    "ending_tsz": 1413636340,
    "original_creation_tsz": 1391007759,
    "last_modified_tsz": 1403095540,
    "price": "230.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "meteorites", "shooting stars", "vermeil beads"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "meteorites", "shooting stars", "vermeil beads"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1401459020,
    "url": "https:\/\/www.etsy.com\/listing\/177533599\/shooting-stars-earrings-meteorites-and?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 173,
    "num_favorers": 15,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 176708080,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151567,
    "title": "Round tahitian pearls trio on silver chain, boho and beach jewelery, st barts island design, tahitian black pearls, cultured pearls.",
    "description": "Simplicity and elegance for this colorfull trio of Tahitian round pearls mounted on a very thin 1mm sterling silver ball chain, The pearl are from 8.5 to 9 mm.\r\n\r\nThe lenght of the necklace is available in : 16 \/ 18 \/ 20 \/ 22 inches.\r\nThe chain is available in : Gold-filled chain \/ silver-chain \/ pink gold chain \/ oxydized silver chain.\r\nThank you to let me know upon buying the lenght AND the chain you want.\r\n\r\nPlease note that the necklace you will receive will be similar to this one, pearls will be same size, same quality, only small variation in colors. pearls are organic, none is similar to the other.\r\n\r\nPearl shape round \r\nPearl quantity 3 \r\nPearl size  8.5mm \r\nLength upon request \r\nMaterial Tahitian pearls \/ chain on request \r\nStyle necklace \r\nPearl grade c\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403095540,
    "ending_tsz": 1413636340,
    "original_creation_tsz": 1390418377,
    "last_modified_tsz": 1403095540,
    "price": "170.00",
    "currency_code": "USD",
    "quantity": 10,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "silver and pearls", "pearl necklace", "tahitian necklace"],
    "category_path": ["Jewelry", "Necklace"],
    "category_path_ids": [68887482, 69151567],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "silver chain", "round tahitian pearls", "pearls and silver"],
    "shop_section_id": 14893388,
    "featured_rank": null,
    "state_tsz": 1400869227,
    "url": "https:\/\/www.etsy.com\/listing\/176708080\/round-tahitian-pearls-trio-on-silver?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 293,
    "num_favorers": 15,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "made_to_order",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": true,
    "used_manufacturer": false
  }, {
    "listing_id": 178731476,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151567,
    "title": "Asteroid leather and tahitian pearl, meteorit, precious leather, beach jewelry, boho, black pearl of tahiti, St Barts island design treasure",
    "description": "Beautiful and genuine black iron M\u00e9t\u00e9orite with smooth fusion surface, mounted on precious leather and using a Tahitian black pearls as clasp.\r\n\r\nDo you want to cary an extraterrestrial material with you ? A testimonial of the diary of all the diarys around your neck ?\r\n\r\nPlease check below for more explanation : \r\n\r\nThe Canyon Diablo meteorite comprises many fragments of the asteroid that impacted at Barringer Crater (Meteor Crater), Arizona, USA, The asteroid fell about 50,000 years ago.The Canyon Diablo crater, and quite likely its iron meterorites, were known to the Indians before the white man came to Arizona. \r\nWhile it has been reported that the area was considered cursed, the fall was almost certainly prior to Indian habitation. The Meteor Crater is a huge hole--about three quarters of a mile wide and 600 feet deep\r\n\r\nPearl grade C \r\nPearl shape half baroque \r\nPearl quantity 1 \r\nMaterial Asteroid \/ black pearl \/ leather \r\nPearl size  10mm \r\nLength 45 cm \r\nStyle Necklace\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1403095539,
    "ending_tsz": 1413636339,
    "original_creation_tsz": 1391895331,
    "last_modified_tsz": 1403095539,
    "price": "300.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "meteorit", "asteroid", "meteorit and leather"],
    "category_path": ["Jewelry", "Necklace"],
    "category_path_ids": [68887482, 69151567],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "meteorit and leather", "meteorit", "asteroid"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1402346442,
    "url": "https:\/\/www.etsy.com\/listing\/178731476\/asteroid-leather-and-tahitian-pearl?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 198,
    "num_favorers": 5,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 191454114,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Braided leather with Keishi natural Tahitian pearls, natural pearls from Tahiti, Australian gold pearl, bohemian inspiration, beach jewelr",
    "description": "Delicate braided leather bracelet  with some inclusion of precious natural Tahitian keishi pearls, using a 10.5mm light gold Australian pearls as clasp.\r\n\r\n A keishi is a nucleus-free pearls form in the cavities where the first generation pearls once grew. They are completely freeform (from a grain of sand per example) and are the closest cultured pearl equivalent to Natural Pearls we can find in the world : A treasure from Mother nature !\r\n\r\nThe Keishis has a great luster; unique Beach jewelery bohemian bracelet !\r\n\r\nStyle Bracelet \r\nMaterial Tahitian Keishi, Leather, Australian pearl \r\nPearl size  10.5 mm \/ 11 to 6 mm \r\nPearl shape Keishi free from and Half-baroque \r\nLength 20.5 cm \r\nPearl quantity 6 \r\nPearl grade C\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1401572817,
    "ending_tsz": 1412113617,
    "original_creation_tsz": 1401572817,
    "last_modified_tsz": 1401579796,
    "price": "390.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather braided", "keishi", "pearls and leather"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "keishi", "pearls and leather", "braided leather"],
    "shop_section_id": 13304093,
    "featured_rank": null,
    "state_tsz": 1401572817,
    "url": "https:\/\/www.etsy.com\/listing\/191454114\/braided-leather-with-keishi-natural?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 121,
    "num_favorers": 13,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 191459781,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Waterfall earrings of shiny Tahitian half baroque pearls, cultured pearls gold filled 14K clasps, St Barth design, bohemian beach style",
    "description": "Waterfall of 10 Shinny Tahitian pearls mounted as earrings on 14k gold filled clasps.\r\n\r\nSailor knots on my precious hand rolled leather, the pearls has very nice luster C+ quality, shinny, all different and so pretty !\r\n\r\nSparkeling and unique chic beach jewelry.\r\n\r\nPearl shape half baroque \r\nPearl quantity 10 \r\nMaterial Tahitian pearls \/ Gold filled 14k hooks \r\nLength 8.5 cm \r\nStyle Earrings \r\nPearl size  8 mm \r\nPearl grade C+\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1401572174,
    "ending_tsz": 1412112974,
    "original_creation_tsz": 1401572174,
    "last_modified_tsz": 1401716003,
    "price": "439.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "pearls and leather", "pearls earrings", "leather earrings"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "pearls earrings", "leather earrings", "pearls and leather"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1401572174,
    "url": "https:\/\/www.etsy.com\/listing\/191459781\/waterfall-earrings-of-shiny-tahitian?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 55,
    "num_favorers": 1,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 190581471,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Bohemian Treasures bracelet on leather, various treasures, cultured pearls on request, MADE TO ORDER !! bohochic beach jewelry St Barth",
    "description": "Bracelet make to order composed with various genuine treasures and a shinny cultured pearls.\r\n\r\nThank you to indicate me if you if you prefer a Black pearl of Tahiti \/ Gold or White pearls from Australia.\r\n\r\nVarious treasures are picked up from my private collection and can includ precious stones, crystals, fossils, seaglass, m\u00e9t\u00e9orites, trade beads, turquoise, keishi ect...following the inspiration of the moment or maybe...your favourite color mood ??!I \r\n\r\nThis bracelet will be mounted with care and traditional sailors knots on my hand rolled precious leather here in St Barth.\r\n\r\nATTENTION:  This offer is for one Bracelet !!!!\r\n\r\nPlease indicate me your wrist size as well as the color of the pearl your prefer .\r\n\r\nUnique !! made to order,  one a a kind creation only for you !!\r\n\r\nPearl shape various \r\nPearl grade C \r\nMaterial cultured pearl \/ treasures \/ leather \r\nStyle Bracelet \r\nLength on request \r\nPearl size  various \r\nPearl quantity 1\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1400857736,
    "ending_tsz": 1411484936,
    "original_creation_tsz": 1400857736,
    "last_modified_tsz": 1401572270,
    "price": "200.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "treasures", "booty", "treasures and pearls"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "treasures and pearls", "pirates booty", "pearls and leather"],
    "shop_section_id": 13309212,
    "featured_rank": 4,
    "state_tsz": 1400857736,
    "url": "https:\/\/www.etsy.com\/listing\/190581471\/bohemian-treasures-bracelet-on-leather?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 132,
    "num_favorers": 10,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": ["Bobo", "Plage"],
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": true,
    "used_manufacturer": false
  }, {
    "listing_id": 190509916,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Genuine piece of eight bracelet, pirates ancient coin on leather and tahitian pearls as clasp, pirates booty, silver coin, cultured pearls",
    "description": "Authentic pirates 1650&#39;s silver coin bracelet : a genuine &quot;piece of 8&quot; which have spend at least 300 years at the bottom of the caribbean ocean, burial patina due to the corrosion of the centuries, on the back a Florenzada cross remain slighly visible.A genuine testimonial of the Caribbean pirates era.\r\n\r\nGenuine piece of 8 mounted on hand rolled precious leather including 1 Round black Tahitian pearl as clasp, visible Florenzada cross, one of a kind bracelet.\r\n\r\n&quot;Cob coins&quot; are rare, difficult to find.\r\n\r\nSome of them are from private collections.\r\nSome others are bought at auction in archaeological foundations and other are the booty of passionate treasure seekers , which are walking miles and miles of beaches, armed with a metal detector and lots of patience... \r\n\r\nPearl quantity 1 \r\nLength adaptable 19 cm \r\nPearl shape round \r\nPearl grade C \r\nStyle bracelet \r\nMaterial silver pirates coin \/ Tahitian pearls \/ leather \r\nPearl size  10.4 mm \r\n\r\nHISTORY : \r\n\r\nFor most people the word shipwreck represents old sunken Spanish galleons, dismasted and rudderless in hurricane seas, their panicked crews helpless and praying as the ships slam into reefs that rip open their fragile hulls and send chests of gold and silver to the bottom. Indeed many Spanish galleons returning to Europe from the Americas met this tragic fate. By some estimates a third of Spain\u2019s treasure ships never made it home. A lot of treasure is still waiting to be recovered.\r\n\r\nBetween 1492 and the early 19th century, Spain extracted  gold, silver, precious gems and other treasures from the Caribbean, Mexican and South American colonies. Treasure and other trade goods were loaded at the new Spanish ports in Panama, Colombia, Ecuador, Mexico, Peru and the Philippines, then shipped to Spain in large armed fleets of galleons.\r\n\r\nThe Spanish colonial mints at Potos\u00ed, Lima, Cartagena, Bogot\u00e1 and Mexico City (plus a few others) labored day and night to produce the irregularly shaped gold and silver coins commonly referred to as macuquinas (crude hammered coins) or \u201ccobs.&quot; It is believed the word &quot;cob&quot; is the simplification of the Spanish phrase &quot;cabo de barra,&quot; meaning &quot;end of the bar,&quot; as the blanks, or planchets, for these coins were actually sliced off the ends of silver bars straight from the mines. The planchets were then trimmed to prescribed weights and struck between crude dies, thus no two cobs are ever exactly alike! That is what makes these &quot;macuquinas&quot; unique and really interesting to collect.\r\n\r\nWhen you talk about &quot;treasure coins,&quot; though, keep in mind that underweight silver coins are very common due to corrosion from salt water and erosion from 300-400 years at the bottom of the sea. \r\n\r\nCobs were minted from the early 1500\u2019s until the mid-18th century.\r\n\r\nBy a royal statute first promulgated in the reign of Charles I of Spain, the official weights of the silver reales were as follows:\r\n\r\n\u00b7 8 reales (cob) = 27.3 grams [0.96 ounces]\r\n\u00b7 4 reales (cob) = 13.65 grams [0.48 ounces]\r\n\u00b7 2 reales (cob) = 6.825 grams [0.24 ounces]\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1400797261,
    "ending_tsz": 1411424461,
    "original_creation_tsz": 1400797261,
    "last_modified_tsz": 1400853636,
    "price": "525.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "cob coin", "silver coin", "pirates coin"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "pirates coin", "silver coin", "cob coin"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1400797261,
    "url": "https:\/\/www.etsy.com\/listing\/190509916\/genuine-piece-of-eight-bracelet-pirates?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 98,
    "num_favorers": 8,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": ["Plage", "Bobo"],
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 188717641,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Wild knots coloful Bracelets of Tahitian pearls OR Australian cultured pearls, beach and leather jewelry, bohemian inspiration, hippie chic",
    "description": "Bracelet make on request composed with 6 Cultured pearls either from Australia or Tahiti knotted with care on my hand rolled precious leather here in St barth.This offer is for one Bracelet !\r\n\r\nPlease indicate me your wrist size, the leather color you want as well as the pearls your prefer (Tahitian black or Australian White or golden).\r\n\r\nAnother pearls is used as claps.On request !! one a a kind creation only for you !!\r\n\r\nLength on request  \r\nPearl grade C \r\nMaterial Tahitian OR Australian pearls \/ leather \r\nPearl shape semi-baroque \/ circled \r\nPearl quantity 6 \r\nStyle bracelet \r\nPearl size  9 mm\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1400780530,
    "ending_tsz": 1411407730,
    "original_creation_tsz": 1399398882,
    "last_modified_tsz": 1400813986,
    "price": "327.00",
    "currency_code": "USD",
    "quantity": 6,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather bracelet", "leather and pearls", "beach bracelet"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather bracelet", "leather and pearls", "beach bracelet"],
    "shop_section_id": 13304093,
    "featured_rank": null,
    "state_tsz": 1399398882,
    "url": "https:\/\/www.etsy.com\/listing\/188717641\/wild-knots-coloful-bracelets-of-tahitian?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 275,
    "num_favorers": 14,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "made_to_order",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": true,
    "used_manufacturer": false
  }, {
    "listing_id": 190263899,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151567,
    "title": "Bohemian treasures necklace, st barth design, boho inspiration, beach jewelry, cultured pearls of Australia and Tahiti, booty treasures",
    "description": "A genuine worldwide treasure around your neck. \r\nThis bohemian inspiration handmade necklace is mounted by hand on Australian leather with ancient beads and Pirates silver cob-coin, rough stone and Precious cultured pearls.\r\n\r\n This one of a kind necklace includ:  \r\n  \r\n -a Genuine silver pirates &quot;pi\u00e8ces of 4&quot;, around 1650 years old\r\n -a Bubble sea glass bead from northen England, rolled by the sea for at least 100 years.\r\n -a genuine rough emerald which i bought from Minas gerais mint, Brazil.\r\n -a huge Australian cultured white pearl of 14.5 mm half baroque, drilled and mounted as a drop\r\n -an Australian shinny gold pearl of 11mm\r\n -a rolled shell from the wild coast of St Barth Island\r\n -a Tahitian pearl of 9.5mm which is used as clasp.\r\n \r\n\r\n A pirates booty  around your neck from 4 continents, the utlimate bohemian chic after beach necklace.\r\n\r\nStyle Necklace \r\nMaterial Cultured pearls \/ worldwide treasures \/ leather \r\nLength 20 cm long \r\nPearl size  9.5 to 14.5 mm \r\nPearl shape Half baroque \r\nPearl quantity 3 \r\nPearl grade C \/ C+\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).n",
    "creation_tsz": 1400617020,
    "ending_tsz": 1411244220,
    "original_creation_tsz": 1400617020,
    "last_modified_tsz": 1400617020,
    "price": "850.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "treasures", "pearls and treasures", "leather and pearls"],
    "category_path": ["Jewelry", "Necklace"],
    "category_path_ids": [68887482, 69151567],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "boho jewelry", "island treasures", "lariat and pearls", "treasures", "leather and pearls", "silver coin", "emerald", "sea glass"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1400617020,
    "url": "https:\/\/www.etsy.com\/listing\/190263899\/bohemian-treasures-necklace-st-barth?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 103,
    "num_favorers": 14,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 190259589,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151567,
    "title": "Australian huge cultured gold pearls grape, st barth style, boho and beach jewelry, cultured pearls, bohemian chic inspiration, organic.",
    "description": "Unique and very natural design for this wonderful grape of 11 enormous genuine Australian gold pearls from 13.5 to 14.5mm mm half baroque, drop and circled, shinny luster, generous and mounted with care on my hand rolled precious leather, here in St Barts island. \r\n\r\n Totally organic, easy, chic and noisy, rough treasures but knotted in a sophisticated way, lightning\u2026a must. \r\n\r\n The necklace is using an 11th Australian pearls of 12 mm as clasp which make the p\u00eeece adaptable from a long sautoir to a crew neck with a falling pearls on the side of the composition, just slide all the pearls and adapt the lenght to the mood of the day.\r\n\r\nStyle necklace \r\nPearl size  12 \/ 14.5 mm \r\nPearl grade C \r\nMaterial Australian gold pearls \/ leather \r\nLength adaptable \r\nPearl shape half baroque \/ circled \r\nPearl quantity\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).l",
    "creation_tsz": 1400615030,
    "ending_tsz": 1411242230,
    "original_creation_tsz": 1400615030,
    "last_modified_tsz": 1400615770,
    "price": "1970.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "gold pearl", "leather and pearls", "organic jewelry"],
    "category_path": ["Jewelry", "Necklace"],
    "category_path_ids": [68887482, 69151567],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "gold pearls", "leather and pearl", "organic jewelry"],
    "shop_section_id": 13304093,
    "featured_rank": null,
    "state_tsz": 1400615030,
    "url": "https:\/\/www.etsy.com\/listing\/190259589\/australian-huge-cultured-gold-pearls?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 95,
    "num_favorers": 1,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 190242612,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Himalayan turquoise bracelet on leather and tahitian pearl as clasp, black pearl of Tahiti, boho and beach jewelry, St Barth design.",
    "description": "Rare and Large turquoise stone from Himalaya \/ Tibet, use in traditional costume decoration mounted on my hand made precious leather with sailor knots and using a Tahitian pearl as clasp.\r\n \r\nThis ancient bead has burial patina, amazing colors, good high grade. I found this stone in a recent travel in india where i went up to Himalaya in Dharamsala. This one of a kind bracelet is using a semi-baroque 11.5 mm Tahitian pearl as clasp.\r\n\r\nPearl shape semi baroque \r\nLength 18.5 cm \r\nPearl grade C \r\nPearl quantity 1 \r\nPearl size  11.5 mm \r\nStyle bracelet \r\nMaterial Himalayan turquoise \/ Tahitian beads \/ leather \r\n\r\nPlease see below for more informations : \r\n\r\nTurquoise is a mineral colored blue by copper or green by iron. \r\nPraised since ancient times for its lustrous opaque qualities, it features in many Tibetan legends .The death mask of Tutankhamun was studded with Turquoise, as were the mosaic masks dedicated to the gods, the fabulous inlaid skulls, shields and power statues of Moctezuma, the last ruler of the Aztecs. \r\n\r\nIt owes its modern name to its arrival in Europe via Turkey; The Victorians loved it. \r\n\r\n For centuries Turquoise has been recognized as possessing the power to protect riders from injury due to falls. First used as amulets by Turkish soldiers, on their persons and attached to their bridles and trappings, it later came to be used for protection against falls of any kind. \r\n\r\nTurquoise is widely appreciated by Tibetans and all through Tibetan history has been prized, valued and worn as jewellery,not only for preserving the family wealth but also for its application in ritual and medicinal practice.\r\n\r\n &quot;Gyu&quot; (pronounced&quot;yu&quot;) the name for turquoise seems to be indigenous, indicating that knowledge of the mineral came from within and notthrough outside influences. To call a turquoise a stone will offend a Tibetan who will exclaim, &quot;this is a turquoise and not a stone!&quot;.\r\nWith the finest inherent colour in mind, perhaps it might help explain a couplet from a Tibetan love-song; &quot;I\u2019d guard her fragrant body, Like white turquoise so rare.&quot;\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1400609623,
    "ending_tsz": 1411236823,
    "original_creation_tsz": 1400609623,
    "last_modified_tsz": 1400609623,
    "price": "370.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "turquoise stone", "himalayan turquoise", "stone and leather"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "stone and leather", "turquoise stone", "himalayan turquoise"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1400609623,
    "url": "https:\/\/www.etsy.com\/listing\/190242612\/himalayan-turquoise-bracelet-on-leather?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 91,
    "num_favorers": 6,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 188718929,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Huge tahitian silver grey pearls bracelet cultured pearls, St Barts island design, leather and beach jewelry, bohemian hippie chic jewelry",
    "description": "Stunning trio of huge and rare circled silver-greyTahitian pearls, mounted as a bracelet on my hand rolled precious leather with traditional sailor knots.\r\n\r\nThis bracelet is using a fourth Tahitian silver pearl as clasp.Silver -grey pearls is quite rare and to have a trio matching of that size even more.\r\n\r\nThe perfect and really chic beach-boho jewelry from St Barts.\r\n\r\nLength 20 cm \r\nPearl grade C  \r\nPearl size  14.5 \/ 11 mm \r\nPearl quantity 4 \r\nPearl shape Circled \r\nMaterial Silver Tahitian pearls \/ leather\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1399399530,
    "ending_tsz": 1410026730,
    "original_creation_tsz": 1399399530,
    "last_modified_tsz": 1399468907,
    "price": "1100.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "pearls and leather", "leather bracelet", "beach bracelet"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather and pearls", "leather bracelet", "beach bracelet"],
    "shop_section_id": 13304093,
    "featured_rank": null,
    "state_tsz": 1399399530,
    "url": "https:\/\/www.etsy.com\/listing\/188718929\/huge-tahitian-silver-grey-pearls?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 144,
    "num_favorers": 18,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": ["Hippie", "Plage"],
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 188715247,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Long earrings of Tahitian pearls, black pearls of Tahiti, boho beach jewelry, St Barts, saint barthelemy design, endless summer, bohemian",
    "description": "Beautiful and long pair of earrings composed with 6 shinny tahitian pearls mounted on my precious hand rolled leather with traditional sailor knots here in St Barthelemy island.\r\n\r\nThe clasp are sterling silver home oxidized. Dark but shinny, organic jewelry with boho inspiration secretely hide in your neck.\r\n\r\nStyle earrings \r\nPearl size  9 \/ 8.5 mm \r\nPearl grade C+ \r\nMaterial leather\/ Tahitian pearls \/ silver clasps \r\nLength 9 cm \r\nPearl quantity 6 \r\nPearl shape Half baroque\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1399397682,
    "ending_tsz": 1410024882,
    "original_creation_tsz": 1399397682,
    "last_modified_tsz": 1399468917,
    "price": "327.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "earrings and pearls", "leather and pearls", "st barts"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather and pearls", "pearls and leather", "pearls earrings"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1399397682,
    "url": "https:\/\/www.etsy.com\/listing\/188715247\/long-earrings-of-tahitian-pearls-black?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 45,
    "num_favorers": 4,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 188320605,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Huge golden Aussie bracelet, st barts design, island of Saint barthelemy, leather and pearls, boho, cultured pearls, beach jewelry, gipsy",
    "description": "Golden huge Australian Pearl using a semi-baroque Aussie pearl as clasp mounted on a knotted hand made precious leather.\r\n\r\nThe pearls have a very generous form, 13.2 mm, deep color, one of a kind.\r\n\r\nPearl quantity 2 \r\nMaterial Australian gold pearls \/ leather \r\nPearl grade C \r\nPearl shape semi-baroque \r\nLength 19 cm \r\nStyle bracelet \r\nPearl size  13.2 \/ 10.5 mm\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1399069450,
    "ending_tsz": 1409696650,
    "original_creation_tsz": 1399069450,
    "last_modified_tsz": 1399123256,
    "price": "480.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather and pearls", "bracelet with pearls", "leather bracelet"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "leather and pearls", "bracelet with pearls", "leather bracelet"],
    "shop_section_id": null,
    "featured_rank": null,
    "state_tsz": 1399069450,
    "url": "https:\/\/www.etsy.com\/listing\/188320605\/huge-golden-aussie-bracelet-st-barts?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 115,
    "num_favorers": 3,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 188317601,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Triple strands bracelet of Tahitian silver pearls, St Barts island, St Barthelemy, cultured tahitian black pearls, organic jewelry, boho.",
    "description": "Beautiful one of a kind bracelet made with 26 rare silver Tahitian pearls and mounted on our hand rolled precious leather, shinny and unique organic jewelry.\r\n\r\nSilver Tahitian pearls are rare and precious.\r\n\r\nAnother silver pearls is used as clasp. A bohemian treasures.\r\n\r\nPearl shape circled \r\nPearl quantity 26 \r\nStyle bracelet \r\nPearl grade C \r\nMaterial Tahitian silver pearls \/ Leather \r\nPearl size  11.5 \/ 9 mm \r\nLength 20 cm\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1399067512,
    "ending_tsz": 1409694712,
    "original_creation_tsz": 1399067512,
    "last_modified_tsz": 1399122486,
    "price": "1150.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "silver pearls", "pearls and leather", "pearls bracelet"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "silver pearls", "leather bracelet", "leather and pearls"],
    "shop_section_id": null,
    "featured_rank": null,
    "state_tsz": 1399067512,
    "url": "https:\/\/www.etsy.com\/listing\/188317601\/triple-strands-bracelet-of-tahitian?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 155,
    "num_favorers": 7,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 173958835,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Hand faceted lemon quartz \/ citrine jewels, leather and silver black pearls, pirates gems, st barts island, boho, beach jewelery.",
    "description": "Genuine lemon quartz \/ citrine gems, Tavernier Cut with high Dome, 26.55 cts hand faceted with care and mounted with my precious leather on silver hooks.Absolutely unique faceting, precious stones with deep natural lemon colors.Pirates precious gems from Caribbean mounted with care.\r\n\r\nMaterial lemon quartz \/ leather \/ silver \r\nStyle earrings \r\nLength 4.5 cm\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1399033873,
    "ending_tsz": 1409661073,
    "original_creation_tsz": 1388251118,
    "last_modified_tsz": 1399033873,
    "price": "200.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "pirates gems", "earring jewels", "citrine crystal"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "lemon quartz", "citrine", "pirates jewels"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1398788420,
    "url": "https:\/\/www.etsy.com\/listing\/173958835\/hand-faceted-lemon-quartz-citrine-jewels?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 238,
    "num_favorers": 25,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 170894773,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "7 seas Gold bracelet, leather and gold, tahitian pearl, beach jewelry, boho jewelry, St barthelemy island, black pearl of tahiti",
    "description": "One of a kind treasures bracelet : 7 seas, 7 pure gold beads mounted on my hand-made precious leather and using a Tahitian semi baroque pearls 9.5 mm as clasp.\r\n\r\nPearl quantity 1 \r\nMaterial gold beads \/ Tahitian black pearls \/ leather \r\nPearl grade C \r\nPearl shape half baroque \r\nLength 19 cm \r\nPearl size  9.5 mm \r\nStyle bracelet \r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1398290620,
    "ending_tsz": 1408831420,
    "original_creation_tsz": 1385559440,
    "last_modified_tsz": 1398290620,
    "price": "670.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "australian pearl", "cultured pearls", "black pearl", "leather jewelry", "leather necklace", "st barts", "golden pearls", "treasures", "caribbean treasures", "gold and leather", "bracelet gold", "gold bead bracelet"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["Tahitian pearl", "australian pearl", "cultured pearls", "black pearl", "leather jewelry", "leather necklace", "st barts", "white pearl", "golden pearls", "treasures", "caribbean treasures", "leather and gold", "gold bead"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1396010420,
    "url": "https:\/\/www.etsy.com\/listing\/170894773\/7-seas-gold-bracelet-leather-and-gold?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 290,
    "num_favorers": 15,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 127376966,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69161131,
    "title": "Turquoise and leather bracelet, South Dakota turquoise bracelet and leather, leather jewelry, boho jewelry, beach jewelry.",
    "description": "Genuine polished turquoise stone from south Dakota mounted on our precious leather and using a hand made turquoise beads as clasp.\r\n\r\nOne of a kind bracelet for a small rist (16 cm). The stone falls on the hand naturally.\r\n\r\nMateria  lturquoise naturelle \/ cuir\r\nLength  16 cm\r\nStyle  bracelet\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1398290619,
    "ending_tsz": 1408831419,
    "original_creation_tsz": 1364138603,
    "last_modified_tsz": 1398290619,
    "price": "160.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["leather and pearls", "tahitian pearls", "leather jewelry", "white pearls", "golden pearls", "treasures", "artifacts", "st barts", "relic", "turquoise beads", "turquoise stone", "leather bracelet", "leather and stone"],
    "category_path": ["Jewelry", "Bracelet", "Stone"],
    "category_path_ids": [68887482, 68888548, 69161131],
    "materials": ["leather and pearls", "leather jewelry", "treasures", "artifacts", "st barts", "relic", "pearl and leather jewelry", "turquoise bead", "perle en turquoise", "turquoise", "cuir", "turquoise et cuir"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1398268224,
    "url": "https:\/\/www.etsy.com\/listing\/127376966\/turquoise-and-leather-bracelet-south?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 844,
    "num_favorers": 69,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 127312800,
    "state": "active",
    "user_id": 18784655,
    "category_id": 68888548,
    "title": "Pearls leather and shell bracelet, Huge saint Lucy&#39;s eye adaptable bracelet with Tahitian pearls and leather, beach jewelry, boho jewelry.",
    "description": "One of a kind bracelet including 3 round Tahitian black pearls and a rare polished white shell mounted on our precious leather.\r\n\r\nA pieces of shell as big as this one is pretty rare and as his own name and legend depending the area. In the most area of Asia calls it as &quot;Shiva Eye Shell&quot; wich have been describes centuries ago in the Mahabharata, the Great Hindu epic.\r\n\r\nOn the other hands, many country in Europe such as France calls this shell as &quot;Saint Lucy&#39;s Eye&quot; and as is own legend.\r\n\r\nOne commune point is to beleive that the spiral is symbolizes of development and motion and is a strong and important symbol for protection against bad energies.\r\n\r\nLength  adaptable\r\nStyle  bracelet\r\nMaterial  polished huge shell \/ Tahitian black pearl \/ leather\r\nPearl shape  ronde\r\nPearl grade  C\r\nPearl quantity  3\r\nPearl size   9 mm\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1398290619,
    "ending_tsz": 1408831419,
    "original_creation_tsz": 1364068628,
    "last_modified_tsz": 1398290619,
    "price": "270.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["leather and pearls", "tahitian pearls", "leather jewelry", "black pearls", "australian pearls", "south sea pearl", "white pearls", "golden pearls", "treasures", "artifacts", "st barts", "relic", "shell jewelry"],
    "category_path": ["Jewelry", "Bracelet"],
    "category_path_ids": [68887482, 68888548],
    "materials": ["leather and pearls", "tahitian pearls", "leather jewelry", "black pearls", "australian pearls", "white pearls", "treasures", "artifacts", "st barts", "relic", "pearl and leather jewelry", "shell"],
    "shop_section_id": 13309212,
    "featured_rank": null,
    "state_tsz": 1398268214,
    "url": "https:\/\/www.etsy.com\/listing\/127312800\/pearls-leather-and-shell-bracelet-huge?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 361,
    "num_favorers": 28,
    "shipping_template_id": 1191654803,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 126998510,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151567,
    "title": "Round Tahitian pearls on leather, adaptable necklace with 1 pearl of Tahiti as satellite, leather jewelry, boho jewelry, beach jewelry.",
    "description": "One of a kind adaptable and versatile necklace using 3 perfect rounds Tahitian black pearls from 12 to 12.5 mm and 1 satellite round pearls of 11.5 mm.\r\n\r\nYou can adapt this necklace to be wear as a chocker or longer, sliding and knotting the satellite (which will fall on your chest or on your back).\r\n\r\nPearl grad  eC\r\nStyle  necklace\r\nPearl shape  round\r\nPearl size   11.5 \/ 12.5 mm\r\nLength  adaptable\r\nMaterial  Tahitian pearls \/ leather\r\nPearl quantity  4\r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n *All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n *SHIPPING : due to my specific location (French West Indies Caribbean \/ St  Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).",
    "creation_tsz": 1398290619,
    "ending_tsz": 1408831419,
    "original_creation_tsz": 1363795378,
    "last_modified_tsz": 1398290619,
    "price": "1060.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["leather and pearls", "leather", "pearls", "tahitian pearls", "treasures", "st barts", "black pearls", "tahitian", "necklace"],
    "category_path": ["Jewelry", "Necklace"],
    "category_path_ids": [68887482, 69151567],
    "materials": ["cuir", "perle de tahiti"],
    "shop_section_id": 13304093,
    "featured_rank": null,
    "state_tsz": 1398268222,
    "url": "https:\/\/www.etsy.com\/listing\/126998510\/round-tahitian-pearls-on-leather?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 1682,
    "num_favorers": 81,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }, {
    "listing_id": 186281282,
    "state": "active",
    "user_id": 18784655,
    "category_id": 69151501,
    "title": "Sapphires and silver cob coin drops, treasures of caribbean, rough sapphires, pirates, hippiechic, bohemian, boho, beach and leather jewelry",
    "description": "Unique pair of earrings made with rough sapphires (which i bought during a recent travel in Jaipur \/ India) and hand-shapped pieces of silver authentic pirates &quot;piece of eight &quot; dated around 1650&#39;s from an english private collection.Visible details remain, please recall that this coins have spend centuries at the bottom of the ocean.These treasures have been mounted  with care on my precious hand rolled leather in the island of St Barts on two silver clasp.\r\n\r\nMaterial Sapphires \/ piece of 8 \/ leather \/ silver clasps \r\nLength 9 cm \r\nStyle earrings \r\n\r\nPlease refer below for the full stone explanation :\r\n\r\n&quot;Cob coins&quot; are rare, difficult to find.\r\nSome of them are from private collections.\r\nSome others are bought at auction in archaeological foundations and other are the booty of passionate treasure seekers , which are walking miles and miles of beaches, armed with a metal detector and lots of patience... \r\n\r\nHISTORY : \r\n\r\nFor most people the word shipwreck represents old sunken Spanish galleons, dismasted and rudderless in hurricane seas, their panicked crews helpless and praying as the ships slam into reefs that rip open their fragile hulls and send chests of gold and silver to the bottom. Indeed many Spanish galleons returning to Europe from the Americas met this tragic fate. By some estimates a third of Spain\u2019s treasure ships never made it home. A lot of treasure is still waiting to be recovered.\r\n\r\nBetween 1492 and the early 19th century, Spain extracted billions and billions of dollars&#39; worth of gold, silver, precious gems and other treasures from the Caribbean, Mexican and South American colonies. Treasure and other trade goods were loaded at the new Spanish ports in Panama, Colombia, Ecuador, Mexico, Peru and the Philippines, then shipped to Spain in large armed fleets of galleons.\r\n\r\nThe Spanish colonial mints at Potos\u00ed, Lima, Cartagena, Bogot\u00e1 and Mexico City (plus a few others) labored day and night to produce the irregularly shaped gold and silver coins commonly referred to as macuquinas (crude hammered coins) or \u201ccobs.&quot; It is believed the word &quot;cob&quot; is the simplification of the Spanish phrase &quot;cabo de barra,&quot; meaning &quot;end of the bar,&quot; as the blanks, or planchets, for these coins were actually sliced off the ends of silver bars straight from the mines. The planchets were then trimmed to prescribed weights and struck between crude dies, thus no two cobs are ever exactly alike! That is what makes these &quot;macuquinas&quot; unique and really interesting to collect.\r\n\r\nWhen you talk about &quot;treasure coins,&quot; though, keep in mind that underweight silver coins are very common due to corrosion from salt water and erosion from 300-400 years at the bottom of the sea. \r\n\r\nCobs were minted from the early 1500\u2019s until the mid-18th century.\r\n\r\nBy a royal statute first promulgated in the reign of Charles I of Spain, the official weights of the silver reales were as follows:\r\n\r\n\u00b7 8 reales (cob) = 27.3 grams [0.96 ounces]\r\n\u00b7 4 reales (cob) = 13.65 grams [0.48 ounces]\r\n\u00b7 2 reales (cob) = 6.825 grams [0.24 ounces] \r\n\r\n*I Guarantee all my treasures genuine or a full refund. You will always be inform of the preparation as well as the shipment of your order.\r\n\r\n*All items are sent out in my hand made treasure gift box, carefully sealed including a personalized calligraphy for the unique opening pleasure of the beneficiary. \r\n\r\n*SHIPPING : due to my specific location (French West Indies Caribbean \/ St Barthelemy island), all my packages are send with registered mail including insurance and signature request. The reception delay is 3 to 8 days for France and 8 to 25 days for any other destinations.\r\n\r\n-DHL (optional) : if you want to receive your order safely in your hand in 3 to 4 business days, I use DHL international shipping with insurance for a participation fee of 35 Dollars, Thank you to advise me before placing your order for adjustment. (buyers are responsible for any and all duties and customs charges that may be incurred).\r\n\r\n.",
    "creation_tsz": 1397573915,
    "ending_tsz": 1408114715,
    "original_creation_tsz": 1397573915,
    "last_modified_tsz": 1401572270,
    "price": "456.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "blue sapphires", "silver cob coin", "sapphire and leather"],
    "category_path": ["Jewelry", "Earrings"],
    "category_path_ids": [68887482, 69151501],
    "materials": ["Tahitian pearl", "Australian pearl", "cultured pearl", "black pearl", "leather jewelry", "st barthelemy", "Beach jewelry", "boho jewelry", "island treasures", "lariat and pearls", "blue sapphires", "silver cob coin", "sapphire and leather"],
    "shop_section_id": 13378668,
    "featured_rank": null,
    "state_tsz": 1397573915,
    "url": "https:\/\/www.etsy.com\/listing\/186281282\/sapphires-and-silver-cob-coin-drops?utm_source=tresorsdestbarth&utm_medium=api&utm_campaign=api",
    "views": 179,
    "num_favorers": 19,
    "shipping_template_id": 1191654103,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2014",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false
  }],
  "params": {
    "limit": 25,
    "offset": 0,
    "page": null,
    "shop_id": "tresorsdestbarth",
    "keywords": null,
    "sort_on": "created",
    "sort_order": "down",
    "min_price": null,
    "max_price": null,
    "color": null,
    "color_accuracy": 0,
    "tags": null,
    "category": null,
    "translate_keywords": "false",
    "include_private": 0
  },
  "type": "Listing",
  "pagination": {
    "effective_limit": 25,
    "effective_offset": 0,
    "next_offset": 25,
    "effective_page": 1,
    "next_page": 2
  }
}
